name: semanticNetworks
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - pip:
    - nbgitpuller
    - sphinx-gallery
    - pandas
    - matplotlib
    - nltk
    - networkx
    - gensim
    - enchant